using System.Buffers.Binary;
using System.Text;
using SkiaSharp;
using Svg.Skia;

// Run from the repository root: dotnet run --project tools/app-icon
const string Dir = "src/gui/icon";
if (!File.Exists(Path.Combine(Dir, "brack.svg")))
{
    Console.Error.WriteLine($"Run this from the repository root ({Dir}/brack.svg is not here).");
    return 1;
}

using var full = Load("brack.svg");
using var small = Load("brack-small.svg");

File.WriteAllBytes(Path.Combine(Dir, "brack.ico"), Ico([16, 20, 24, 32, 40, 48, 64, 256]));
File.WriteAllBytes(Path.Combine(Dir, "brack.icns"), Icns([
    ("icp4", 16), ("ic11", 32), ("icp5", 32), ("ic12", 64), ("icp6", 64), ("ic07", 128),
    ("ic13", 256), ("ic08", 256), ("ic14", 512), ("ic09", 512), ("ic10", 1024)]));
Directory.CreateDirectory(Path.Combine(Dir, "png"));
foreach (var px in new[] { 16, 24, 32, 48, 64, 128, 256, 512 })
{
    File.WriteAllBytes(Path.Combine(Dir, "png", $"brack-{px}.png"), Png(Render(px, false)));
}
File.WriteAllText(Path.Combine(Dir, "window_icon.inc"), WindowIcons([16, 32, 48, 64]));
return 0;

SKSvg Load(string name)
{
    var svg = new SKSvg();
    if (svg.Load(Path.Combine(Dir, name)) is null) throw new InvalidDataException($"cannot read {name}");
    return svg;
}

// Below 48 px the full drawing's buttons, screws and LCD text blur into noise.
SKPicture Drawing(int px) => (px <= 32 ? small : full).Picture!;

SKImage Render(int px, bool macGrid)
{
    using var surface = SKSurface.Create(new SKImageInfo(px, px, SKColorType.Rgba8888, SKAlphaType.Premul));
    var canvas = surface.Canvas;
    canvas.Clear(SKColors.Transparent);
    // macOS app icons sit on Apple's icon grid: the plate is 824 of 1024 px, centred, so the
    // icon matches the others in the Dock. Windows and Linux icons fill their square.
    var margin = macGrid ? px * 100f / 1024 : 0;
    canvas.Translate(margin, margin);
    canvas.Scale((px - 2 * margin) / 1024f);
    canvas.DrawPicture(Drawing(px));
    return surface.Snapshot();
}

static byte[] Png(SKImage image)
{
    using (image)
    using (var data = image.Encode(SKEncodedImageFormat.Png, 100))
    {
        return data.ToArray();
    }
}

// Each image is a PNG, which Windows reads at every size since Vista.
byte[] Ico(int[] sizes)
{
    var images = sizes.Select(px => Png(Render(px, false))).ToArray();
    using var stream = new MemoryStream();
    using var w = new BinaryWriter(stream);
    w.Write((ushort)0);
    w.Write((ushort)1);
    w.Write((ushort)sizes.Length);
    var offset = 6 + 16 * sizes.Length;
    for (var i = 0; i < sizes.Length; i++)
    {
        w.Write((byte)(sizes[i] >= 256 ? 0 : sizes[i]));
        w.Write((byte)(sizes[i] >= 256 ? 0 : sizes[i]));
        w.Write((byte)0);
        w.Write((byte)0);
        w.Write((ushort)1);
        w.Write((ushort)32);
        w.Write(images[i].Length);
        w.Write(offset);
        offset += images[i].Length;
    }
    foreach (var image in images) w.Write(image);
    return stream.ToArray();
}

byte[] Icns((string Type, int Px)[] entries)
{
    var chunks = entries.Select(e => (e.Type, Data: Png(Render(e.Px, true)))).ToArray();
    using var stream = new MemoryStream();
    void Header(string type, int length)
    {
        stream.Write(Encoding.ASCII.GetBytes(type));
        Span<byte> be = stackalloc byte[4];
        BinaryPrimitives.WriteInt32BigEndian(be, length);
        stream.Write(be);
    }
    Header("icns", 8 + chunks.Sum(c => 8 + c.Data.Length));
    foreach (var (type, data) in chunks)
    {
        Header(type, 8 + data.Length);
        stream.Write(data);
    }
    return stream.ToArray();
}

// X11 takes a window's icon as pixels (_NET_WM_ICON), and the GUI has no PNG decoder.
string WindowIcons(int[] sizes)
{
    var text = new StringBuilder();
    text.Append("// Generated by tools/app-icon from brack.svg and brack-small.svg: the window icons for\n");
    text.Append("// glfwSetWindowIcon, as unpremultiplied RGBA rows.\n");
    foreach (var px in sizes)
    {
        using var image = Render(px, false);
        using var bitmap = new SKBitmap(new SKImageInfo(px, px, SKColorType.Rgba8888, SKAlphaType.Unpremul));
        if (!image.ReadPixels(bitmap.Info, bitmap.GetPixels(), bitmap.RowBytes, 0, 0))
        {
            throw new InvalidOperationException($"cannot read the {px} px pixels");
        }
        text.Append($"static unsigned char kWindowIcon{px}[] = {{\n");
        foreach (var row in bitmap.Bytes.Chunk(24))
        {
            text.Append(string.Join(",", row.Select(b => $"0x{b:x2}"))).Append(",\n");
        }
        text.Append("};\n");
    }
    text.Append("static const GLFWimage kWindowIcons[] = {\n");
    foreach (var px in sizes) text.Append($"    {{{px}, {px}, kWindowIcon{px}}},\n");
    text.Append("};\n");
    return text.ToString();
}
