cmake_minimum_required(VERSION 3.25)
# cmake -DREADELF=<readelf> -DNEWEST=<x of glibc 2.x> -DFILE=<program, or a folder> -P check_glibc_needs.cmake
# Fails when FILE, or an ELF file in the folder, needs a newer C library than glibc 2.NEWEST:
# a GLIBC_2.x above it, GLIBC_ABI_DT_RELR (glibc 2.36) above it, or any other GLIBC_ABI_* tag.
if(IS_DIRECTORY "${FILE}")
  file(GLOB_RECURSE files LIST_DIRECTORIES false "${FILE}/*")
else()
  set(files "${FILE}")
endif()
set(failed "")
foreach(file IN LISTS files)
  file(READ "${file}" magic LIMIT 4 HEX)
  if(NOT magic STREQUAL "7f454c46")
    continue()
  endif()
  execute_process(COMMAND "${READELF}" -W -V "${file}" OUTPUT_VARIABLE out COMMAND_ERROR_IS_FATAL ANY)
  string(REGEX MATCHALL "Name: GLIBC_[A-Z0-9_.]+" needs "${out}")
  set(too_new "")
  set(newest 0)
  foreach(need IN LISTS needs)
    string(SUBSTRING "${need}" 6 -1 need)
    if(need MATCHES "^GLIBC_2\\.([0-9]+)")
      set(minor ${CMAKE_MATCH_1})
    elseif(need STREQUAL "GLIBC_ABI_DT_RELR")
      set(minor 36)
    else()
      set(minor 999)
    endif()
    if(minor GREATER NEWEST)
      list(APPEND too_new "${need}")
    elseif(minor GREATER newest)
      set(newest ${minor})
    endif()
  endforeach()
  if(too_new)
    list(REMOVE_DUPLICATES too_new)
    list(SORT too_new COMPARE NATURAL)
    list(JOIN too_new " " too_new)
    list(APPEND failed "${file} needs ${too_new}")
  elseif(IS_DIRECTORY "${FILE}")
    message(STATUS "${file}: glibc 2.${newest}")
  endif()
endforeach()
if(failed)
  list(JOIN failed "\n" failed)
  message(FATAL_ERROR "${failed}\nThat is newer than glibc 2.${NEWEST}, so they would not start there.")
endif()
